# Generated by Django 3.1.3 on 2023-11-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
