# Generated by Django 4.2.7 on 2023-11-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Counts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.TextField()),
                ("clinic", models.IntegerField()),
                ("healthcenter", models.IntegerField()),
                ("pharmacy", models.IntegerField()),
                ("dentist", models.IntegerField()),
                ("oriental", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.TextField()),
                ("sum", models.IntegerField()),
                ("genhos", models.IntegerField()),
                ("hos", models.IntegerField()),
                ("nurs", models.IntegerField()),
                ("mental", models.IntegerField()),
                ("clinic", models.IntegerField()),
                ("Public", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(max_length=255)),
                ("hospital", models.IntegerField()),
                ("doctor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicalinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("hospital", models.IntegerField()),
                ("doctor", models.IntegerField()),
                ("nurse", models.IntegerField()),
                ("patient", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Population",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.TextField()),
                ("total", models.IntegerField()),
                ("m", models.IntegerField()),
                ("f", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sejong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("type", models.TextField()),
                ("phone", models.TextField()),
                ("code", models.IntegerField()),
                ("address", models.TextField()),
                ("address1", models.TextField()),
                ("department", models.TextField()),
            ],
        ),
    ]
