# Generated by Django 3.1.3 on 2023-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_auto_20231115_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sejong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('type', models.TextField()),
                ('phone', models.TextField()),
                ('code', models.IntegerField()),
                ('address', models.TextField()),
                ('address1', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
