# Generated by Django 3.1.3 on 2023-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_sejong'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField()),
                ('sum', models.IntegerField()),
                ('genhos', models.IntegerField()),
                ('hos', models.IntegerField()),
                ('nurs', models.IntegerField()),
                ('mental', models.IntegerField()),
                ('clinic', models.IntegerField()),
                ('Public', models.IntegerField()),
            ],
        ),
    ]
