# Generated by Django 3.1.3 on 2023-11-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inpatrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
                ('disease', models.TextField()),
                ('count', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outpatrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
                ('disease', models.TextField()),
                ('count', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regionpop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.TextField()),
                ('mage0s', models.IntegerField()),
                ('mage10s', models.IntegerField()),
                ('mage20s', models.IntegerField()),
                ('mage30s', models.IntegerField()),
                ('mage40s', models.IntegerField()),
                ('mage50s', models.IntegerField()),
                ('mage60s', models.IntegerField()),
                ('mage70s', models.IntegerField()),
                ('fage0s', models.IntegerField()),
                ('fage10s', models.IntegerField()),
                ('fage20s', models.IntegerField()),
                ('fage30s', models.IntegerField()),
                ('fage40s', models.IntegerField()),
                ('fage50s', models.IntegerField()),
                ('fage60s', models.IntegerField()),
                ('fage70s', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ToCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('tocost', models.IntegerField()),
            ],
        ),
    ]
