# Generated by Django 3.1.3 on 2023-11-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0005_inpatrank_outpatrank_regionpop_tocost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumTre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('numtre', models.IntegerField()),
            ],
        ),
    ]
