# Generated by Django 3.1.3 on 2023-12-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_numtre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sejong',
            name='address1',
        ),
        migrations.AddField(
            model_name='sejong',
            name='lat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sejong',
            name='long',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
