# Generated by Django 3.1.3 on 2023-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0008_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='region',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
