# Generated by Django 4.2.7 on 2023-11-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finalapp", "0003_sejong"),
    ]

    operations = [
        migrations.AddField(
            model_name="counts",
            name="to_hp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="counts",
            name="to_people",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="counts",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicalinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sejong",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
