# Generated by Django 4.2.7 on 2023-11-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finalapp", "0004_counts_to_hp_counts_to_people_alter_counts_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumTre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("numtre", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ToCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("tocost", models.IntegerField()),
            ],
        ),
    ]
