# Generated by Django 4.2.7 on 2023-11-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finalapp", "0005_numtre_tocost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regionpop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regions", models.TextField()),
                ("mage0s", models.IntegerField()),
                ("mage10s", models.IntegerField()),
                ("mage20s", models.IntegerField()),
                ("mage30s", models.IntegerField()),
                ("mage40s", models.IntegerField()),
                ("mage50s", models.IntegerField()),
                ("mage60s", models.IntegerField()),
                ("mage70s", models.IntegerField()),
                ("fage0s", models.IntegerField()),
                ("fage10s", models.IntegerField()),
                ("fage20s", models.IntegerField()),
                ("fage30s", models.IntegerField()),
                ("fage40s", models.IntegerField()),
                ("fage50s", models.IntegerField()),
                ("fage60s", models.IntegerField()),
                ("fage70s", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
    ]
