# Generated by Django 4.2.7 on 2023-11-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finalapp", "0006_regionpop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.TextField()),
                ("sum", models.IntegerField()),
                ("genhos", models.IntegerField()),
                ("hos", models.IntegerField()),
                ("nurs", models.IntegerField()),
                ("mental", models.IntegerField()),
                ("clinic", models.IntegerField()),
                ("Public", models.IntegerField()),
            ],
        ),
    ]
